/** Top Sales */
export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';

/** Goods Catalog */
export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';

export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';

/** Catalog Categories */
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const CHANGE_ACTIVE_CATEGORY = 'CHANGE_ACTIVE_CATEGORY';

/** Search on Header */
export const CLICK_HEADER_SEARCH = 'CLICK_HEADER_SEARCH';
export const CHANGE_HEADER_SEARCH_TEXT = 'CHANGE_HEADER_SEARCH_TEXT';
export const REDIRECT_TO_CATALOG_WITH_SEARCH = 'REDIRECT_TO_CATALOG_WITH_SEARCH';

/** Good */
export const FETCH_GOOD_REQUEST = 'FETCH_GOOD_REQUEST';
export const FETCH_GOOD_SUCCESS = 'FETCH_GOOD_SUCCESS';
export const FETCH_GOOD_FAILURE = 'FETCH_GOOD_FAILURE';
export const CHANGE_GOOD_SELECTED_SIZE = 'CHANGE_GOOD_SELECTED_SIZE';
export const CHANGE_GOOD_QTY_BY = 'CHANGE_GOOD_QTY_BY';

/** CART */
export const PUT_GOOD_INTO_CART = 'PUT_GOOD_INTO_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const ORDER_CART_ITEMS_REQUEST = 'ORDER_CART_ITEMS_REQUEST';
export const ORDER_CART_ITEMS_SUCCESS = 'ORDER_CART_ITEMS_SUCCESS';
export const ORDER_CART_ITEMS_FAILURE = 'ORDER_CART_ITEMS_FAILURE';

export const CHANGE_BUYER_ADDRESS = 'CHANGE_BUYER_ADDRESS';
export const CHANGE_BUYER_PHONE = 'CHANGE_BUYER_PHONE';
export const CHANGE_BUYER_AGREE = 'CHANGE_BUYER_AGREE';